import time
print("Welcome to my amazing game (Not like Advaith.Basireddy's)")
print("This game is about story telling")
d = input("What's your name  ")
j = input("What do you want to name your charecter")
print("Choose your weponry,", d)
print("1. No weapen")
print("2. Daggers")
print("3. Bow")
print("4. Sword")
print("5. Gun")
a = int(input("Choose your bloody weapon  "))
if a == 1:
    print("Ok. No weapen")
    print("Which shield do you choose")
    b = int(input("1 = metal, 2 = wooden, 3 = no weapon.  "))
    if b == 1:
        print("Ok, it is metal")
        print("1. Square shaped")
        print("2. Diamond shaped")
        print("3. Rectangluar shaped")
        print("4. Ovalar shaped")
        c = int(input("What do you want to choose  "))
        if c == 1:
            print("Ok. Square shaped")
            print("Now the story BEGINS!")
            print("You were born in an alien planet and you were sent to Earth at the age 2")
            print("You had super powers before")
            print("But your arch enimie took them all. But he couldn't kill you")
            print("Because you were too strong")
            print("Now, he wants to rule Earth")
            print("The world depends on you,", d)
            print("No one should speak 'his' name. We call him 'human-evil'")
            print("Human-evil's name is Ad-A-Adv-Advaith.Basireddy")
            print("If you speak human-evils name 5 times you you will be cursed")
            time.sleep(5)
            print("Oh no human-evils minion's minion is coming. Tata bye-bye!")
            print("1 = Call your best friend as back up(he will come in 1 min)")
            print("2 = Fight with her")
            print("3 = Run away")
            print("4 = Call your company as back up(2 min & 10 persons)")
            print("5 = Let her kill you")
            e = int(input("What do you choose  "))
            if e == 1:
                print("Oh no she's asking you to fight with her")
                print("1 = Fight with her")
                print("2 = Run away")
                print("3 = Let her kill you")
                f = int(input("What do you do  "))
                if f == 1:
                    print("Ok. Fight")
                    time.sleep(5)
                    print("Now you win and back up comes and arrests her")
                elif f == 2:
                    print("Now you run of far and you see your back up")
                    print("1.= Go with him and fight her")
                    print("2.= Ask him to run with you")
                    print("3.= Ask him only to fight her")
                    g = int(input("What do you do  "))
                    if g == 1:
                        print("Ok. Fighting")
                        time.sleep(2)
                        print("Now your best friend dies")
                        print("1 Run away")
                        print("2 Keep fighting")
                        h = int(input("Choose one  "))
                        if h == 1:
                            print("Now you see a 'HUMAN-EVIL'!")
                            print("He kills you")
                            print("Thanks for playing this", d)
                            print("This is the end of version 1.0")
                            exit("Tata bye-bye")
                        elif h == 2:
                            print("Ok. Fighting")
                            time.sleep(5)
                            print("You win!")
                        else:
                            print("Try again!")
                            exit()
                    elif g == 2:
                        print("Now you see a 'HUMAN-EVIL'!")
                        print("He kills you and her")
                        print("Thanks for playing this", d)
                        print("This is the end of version 1.0")
                        exit("Tata bye-bye")
                    else:
                        print("He says,'Ok, you stay here.'")
                        print("And he goes to fight her")
                        print("Now you see a 'HUMAN-EVIL'!")
                        print("He kills you")
                        print("Thanks for playing this", d)
                        print("This is the end of version 1.0")
                        exit("Tata bye-bye")
                else:
                    print("Now you are stabbed and in 5 seconds you'll be killed")
                    time.sleep(5)
                    print("Now your best friend comes and sees this and kills her")
                    print("He takes you to the hospital")
                    print("The doctors say that because you are not from Earth they don't know your organs")
                    print("Now you see a 'HUMAN-EVIL'!")
                    print("He kills you")
                    print("Thanks for playing this", d)
                    print("This is the end of version 1.0")
                    exit("Tata bye-bye")
            elif e == 2:
                print("Ok. Fighting")
                time.sleep(2)
                print("She stabs your leg and gets a shock cause you are an alien")
                print("Now she's down for a few mins")
                print("1 = Call your friend as back up(2 min)")
                print("2 = Call your company as back up(4 min)")
                print("3 = Let her wake up and kill you(5 min)")
                i = int(input("Which one  "))
                if i == 1:
                    print("You pick your phone and call him")
                    print("He tells,'Ok I'll reach there in 2 min, google maps'.")
                    time.sleep(2)
                    print("Now, human-evil sees him")
                    print("He fights hi, but he looses. Then human-evil kills him")
                    print("Now, she gets up from her shock and shots you")
                    print("Now you are dead")
                    print("Thanks for playing this", d)
                    print("This is the end of version 1.0")
                    exit("Tata bye-bye")
                elif i == 2:
                    print("You pick your phone and call them")
                    print("They tells,'Ok I'll reach there in 4 min, google maps'.")
                    time.sleep(4)
                    print("Now, human-evil sees them")
                    print("Now, they fight against them")
                    print("Then they stab human-evil's knee")
                    print("Human-evil fell and your company is running to you")
                    print("Now, they have arrived to save you")
                    print("Now, she gets up from the shock")
                    print("Now Your crew kills her")
                else:
                    time.sleep(5)
                    print("Now she kills you")
                    print("Thanks for playing this", d)
                    exit()
            elif e == 3:
                print("Ok. Running")
                print("You will take 5 sec to run away")
                time.sleep(5)
                print("Now your arch enemie is in front ")
                print("What do you do")
                print("1. Fight him")
                print("2. Run back and fight his minion")
                print("3. Call for help(2 min)")
                print("4. Die on spot")
                k = int(input("Which one do you choose  "))
                if k == 1:
                    print("Ok fighting")
                    time.sleep(5)
                    print("Oh! You died")
                    print("I forgot to warn you, he is stronger")
                    print("Thanks for playing this", d)
                    exit("Tata, bye-bye")
                elif k==2:
                    print("Ok. Running back")
                    time.sleep(2)
                    print("I forgot to warn you, he is faster")
                    print("He has caught you and killed you")
                    print("Thanks for playing this", d)
                    exit("Tata, bye-bye")
                elif k==3:
                    print("Ok. You pick your phone and call help")
                    print("But human-evil kills you before they come")
                    print("Thanks for playing this", d)
                    exit("Tata, bye-bye")
                else:
                    print("Ok. Dying")
                    print("Thanks for playing this", d)
                    exit("Tata, bye-bye")
            elif e == 4:
                print("Oh no she's asking you to fight with her")
                print("1 = Fight with her")
                print("2 = Run away")
                print("3 = Let her kill you")
                f = int(input("What do you do  "))
                if f == 1:
                    print("Ok. Fight")
                    time.sleep(5)
                    print("Now you win and back up comes and arrests her")
                elif f == 2:
                    print("Now you run of far and you see your back up")
                    print("1.= Go with him and fight her")
                    print("2.= Ask him to run with you")
                    print("3.= Ask him only to fight her")
                    g = int(input("What do you do  "))
                    if g == 1:
                        print("Ok. Fighting")
                        time.sleep(2)
                        print("Now your best friend dies")
                        print("1 Run away")
                        print("2 Keep fighting")
                        h = int(input("Choose one  "))
                        if h == 1:
                            print("Now you see a 'HUMAN-EVIL'!")
                            print("He kills you")
                            print("Thanks for playing this", d)
                            print("This is the end of version 1.0")
                            exit("Tata bye-bye")
                        elif h == 2:
                            print("Ok. Fighting")
                            time.sleep(5)
                            print("You win!")
                        else:
                            print("Try again!")
                            exit()
                    elif g == 2:
                        print("Now you see a 'HUMAN-EVIL'!")
                        print("He kills you and her")
                        print("Thanks for playing this", d)
                        print("This is the end of version 1.0")
                        exit("Tata bye-bye")
                    else:
                        print("He says,'Ok, you stay here.'")
                        print("And he goes to fight her")
                        print("Now you see a 'HUMAN-EVIL'!")
                        print("He kills you")
                        print("Thanks for playing this", d)
                        print("This is the end of version 1.0")
                        exit("Tata bye-bye")
                else:
                    print("Now you are stabbed and in 5 seconds you'll be killed")
                    time.sleep(5)
                    print("Now your best friend comes and sees this and kills her")
                    print("He takes you to the hospital")
                    print("The doctors say that because you are not from Earth they don't know your organs")
                    print("Now you see a 'HUMAN-EVIL'!")
                    print("He kills you")
                    print("Thanks for playing this", d)
                    print("This is the end of version 1.0")
                    exit("Tata bye-bye")
            else:
                print("Ok. Killing")
                time.sleep(2)
                print("Thanks for playing this game", d)
                exit("Tata, bye-bye")